import { PERMISSIONS } from "@/constants/permissions";

export const PERSONAL_DASHBOARD_PERMISSIONS = {
  base: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QUALITY_DASHBOARD_READ,
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.SECURITY_DASHBOARD_READ,
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
  ],
  testing: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.PENTEST_PROJECTS_READ,
    PERMISSIONS.PENTEST_VULNERABILITIES_READ,
  ],
  qa: [PERMISSIONS.QA_DASHBOARD_READ, PERMISSIONS.QA_PROJECTS_READ],
  quality: [PERMISSIONS.QUALITY_DASHBOARD_READ, PERMISSIONS.QUALITY_PROJECTS_READ],
  devops: [PERMISSIONS.DEVOPS_DASHBOARD_READ, PERMISSIONS.DEVOPS_PROJECTS_READ],
  security: [PERMISSIONS.SECURITY_DASHBOARD_READ, PERMISSIONS.SECURITY_PROJECTS_READ],
  representative: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.REPRESENTATIVE_PROJECTS_READ,
  ],
} as const;
