import { PERMISSIONS, type Permission } from "./permissions.js";
import { ROLES, type Role } from "./roles.js";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.ADMIN_SYSTEM_MANAGE,
    PERMISSIONS.ADMIN_DASHBOARD_READ,
    PERMISSIONS.ADMIN_USERS_READ,
    PERMISSIONS.ADMIN_USERS_CREATE,
    PERMISSIONS.ADMIN_USERS_UPDATE,
    PERMISSIONS.ADMIN_USERS_DELETE,
    PERMISSIONS.ADMIN_ROLES_READ,
    PERMISSIONS.ADMIN_ROLES_UPDATE,
    PERMISSIONS.ADMIN_AUDIT_READ,
    PERMISSIONS.ADMIN_PROJECTS_CREATE,
  ],
  [ROLES.PENTESTER]: [
    PERMISSIONS.PENTEST_DASHBOARD_READ,
    PERMISSIONS.PENTEST_PROJECTS_READ,
    PERMISSIONS.PENTEST_VULNERABILITIES_READ,
    PERMISSIONS.PENTEST_VULNERABILITIES_CREATE,
    PERMISSIONS.PENTEST_VULNERABILITIES_UPDATE,
    PERMISSIONS.PENTEST_REPORTS_EXPORT,
  ],
  [ROLES.DEVOPS]: [
    PERMISSIONS.DEVOPS_DASHBOARD_READ,
    PERMISSIONS.DEVOPS_PROJECTS_READ,
    PERMISSIONS.DEVOPS_DEPLOYMENTS_READ,
    PERMISSIONS.DEVOPS_DEPLOYMENTS_CREATE,
    PERMISSIONS.DEVOPS_DEPLOYMENTS_UPDATE,
    PERMISSIONS.DEVOPS_SERVERS_READ,
  ],
  [ROLES.REPRESENTATIVE]: [
    PERMISSIONS.REPRESENTATIVE_DASHBOARD_READ,
    PERMISSIONS.REPRESENTATIVE_PROJECTS_READ,
    PERMISSIONS.REPRESENTATIVE_TICKETS_READ,
    PERMISSIONS.REPRESENTATIVE_TICKETS_CREATE,
    PERMISSIONS.REPRESENTATIVE_TICKETS_UPDATE,
  ],
  [ROLES.QA]: [
    PERMISSIONS.QA_DASHBOARD_READ,
    PERMISSIONS.QA_PROJECTS_READ,
    PERMISSIONS.QA_TEST_CASES_READ,
    PERMISSIONS.QA_TEST_CASES_CREATE,
    PERMISSIONS.QA_TEST_CASES_UPDATE,
    PERMISSIONS.QA_VULNERABILITIES_READ,
  ],
  [ROLES.PROJECT_MANAGER_SECURITY]: [
    PERMISSIONS.SECURITY_DASHBOARD_READ,
    PERMISSIONS.SECURITY_PROJECTS_READ,
    PERMISSIONS.SECURITY_PROJECTS_UPDATE,
    PERMISSIONS.SECURITY_PROJECTS_ASSIGN,
    PERMISSIONS.SECURITY_PROJECTS_MANAGE,
    PERMISSIONS.SECURITY_PENTESTS_READ,
    PERMISSIONS.SECURITY_VULNERABILITIES_READ,
    PERMISSIONS.SECURITY_FINDINGS_REVIEW,
    PERMISSIONS.SECURITY_REPORTS_EXPORT,
  ],
  [ROLES.PROJECT_MANAGER_QA]: [
    PERMISSIONS.QUALITY_DASHBOARD_READ,
    PERMISSIONS.QUALITY_PROJECTS_READ,
    PERMISSIONS.QUALITY_PROJECTS_UPDATE,
    PERMISSIONS.QUALITY_PROJECTS_ASSIGN,
    PERMISSIONS.QUALITY_PROJECTS_MANAGE,
    PERMISSIONS.QUALITY_QA_READ,
    PERMISSIONS.QUALITY_TEST_CASES_READ,
    PERMISSIONS.QUALITY_TEST_CASES_UPDATE,
  ],
};

export function getPermissionsFromRoles(roles: Role[] = []): Permission[] {
  return Array.from(new Set(roles.flatMap((role) => ROLE_PERMISSIONS[role] || [])));
}
