export {
  ALL_PERMISSIONS,
  LEGACY_PERMISSION_ALIASES,
  PERMISSIONS,
  PERMISSION_ACTIONS,
  PERMISSION_DOMAINS,
  PERMISSION_KEY_PATTERN,
  PERMISSION_REGISTRY,
  PERMISSION_SCOPES,
  isAdminPermission,
  isPermissionKey,
  normalizePermissionKey,
  type PermissionAction,
  type PermissionDefinition,
  type PermissionDomain,
  type PermissionScope,
  type Permission,
} from "@role-dashboard/authz";
