export const UPLOADS = {
  AVATAR_FIELD: "file",
  AVATAR_FIELD_ALIAS: "avatar",
  MAX_IMAGE_SIZE_BYTES: 2 * 1024 * 1024,
  IMAGE_MIME_PREFIX: "image/",
  PUBLIC_PATH: (filename: string) => `/uploads/${filename}`,
  POC_PATH: (filename: string) => `/api/pentest/pocs/${encodeURIComponent(filename)}`,
  POC_FIELD: "pocs",
  REQUEST_HEADERS_FILE_FIELD: "requestHeadersFile",
  MAX_REQUEST_HEADERS_FILE_SIZE_BYTES: 1024 * 1024,
  REQUEST_HEADERS_FILE_MIME_TYPES: ["text/plain", "application/octet-stream"],
  MAX_POC_FILES: 10,
  MAX_POC_FILE_SIZE_BYTES: 100 * 1024 * 1024,
  MAX_POC_IMAGE_SIZE_BYTES: 10 * 1024 * 1024,
  MAX_POC_DOCUMENT_SIZE_BYTES: 20 * 1024 * 1024,
  MAX_POC_TOTAL_SIZE_BYTES: 250 * 1024 * 1024,
  MAX_POC_FIELDS: 30,
  MAX_POC_FIELD_SIZE_BYTES: 256 * 1024,
  MAX_ORIGINAL_NAME_LENGTH: 255,
  POC_MIME_TYPES: [
    "image/jpeg", "image/png", "image/webp", "image/gif",
    "video/mp4", "video/webm", "video/quicktime",
    "application/pdf", "application/msword",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "application/vnd.ms-excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "application/vnd.ms-powerpoint",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    "text/plain", "text/csv",
  ],
  POC_EXTENSIONS: {
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
    "image/gif": ".gif",
    "video/mp4": ".mp4",
    "video/webm": ".webm",
    "video/quicktime": ".mov",
    "application/pdf": ".pdf",
    "application/msword": ".doc",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
    "application/vnd.ms-excel": ".xls",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
    "application/vnd.ms-powerpoint": ".ppt",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
    "text/plain": ".txt",
    "text/csv": ".csv",
  },
} as const;
